### PR TITLE
Update Back-End

### PR DESCRIPTION
**Pull request by AhmedBenSalem91**

### CODE REVIEW

**Comment by AhmedBenSalem91** [comment]
ok

**Review by AhmedBenSalem91 — COMMENTED** [review]
UpdateBack-end

**Review by Hamidkacem — COMMENTED** [review]
fix back-end admin

**Review by AhmedBenSalem91 — COMMENTED** [review]
back-end

**Review by AhmedBenSalem91 — COMMENTED** [review]
jkkjk

**Comment by AhmedBenSalem91** [comment]
jkhj

**Pull request closed without merging**
